Tutorial Adjustment
ICB-DCM/cOmicsArt pull request #398
Opened 2024-11-14 21:11 UTC by PaulJonasJost

Fixed ID issue in cicerone. Fixed Markdown rendering instead of HTML rendering. Closes #392

2024-11-15 09:27 UTC, LeaSeep requested changes

2024-11-15 09:27 UTC, LeaSeep commented on program/shinyApp/R/C.R
> +    description = HTML("Here we have 1 parameter to set.<br>Select <strong>Youtube Tutorial<\strong> from the dropdown menu.")
```suggestion
    description = HTML("Here we have 1 parameter to set.<br>Select <strong>Youtube Tutorial</strong> from the dropdown menu.")
```
I think this is why the test fails

2024-11-15 09:36 UTC, PaulJonasJost commented
is the faling of the test your only reason to request changes? In which case a rereview is not necessary for me, would then  overrule and merge if it goes through

2024-11-18 12:55 UTC, LeaSeep approved these changes

2024-11-18 16:17 UTC, merged